version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:12.10
    steps:
      - checkout
      - run: sudo npm install -g --silent netlify-cli
      - run: netlify deploy --dir=./public -p


workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

